[package]
name = "petumec"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "petumec_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# прозрачность окна на macos работает только с macos-private-api
# tray-icon включает фичу иконки в менюбаре
# image-png для загрузки png-картинки
tauri = { version = "2", features = ["macos-private-api", "tray-icon", "image-png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# зависимости только для macos
[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
# импортируем из appkit (UI-фреймворк от Apple) классы:
#   - NSWindow: оболочка окна на экране, не рендерит, а взаимодействует с WindowServer,
#      обрабатывает оконные события по типу ресайза или фуллскрина
#   - NSPanel: это подкласс NSWindow, нужен для второстепенных окон приложения,
#      обладает специфичными свойствами, например позиция в спейсе с полноэкранным приложением
#      и отсутствие фокуса как отдельное приложение в нашем кейсе
#   - NSResponder: отвечает за обработку пользовательских событий, клики, клавиши клавиатуры и т.п.
#
# иерархия классов:
#   до NSPanel: NSObject -> NSResponder -> NSWindow -> NSPanel
#
# NSObject: корневой класс в иерархии appkit, владеет методами работы с классами
#
# каждый класс в цепочке наследования нужно включать отдельной фичей, чтобы он работал
# (кроме NSObject — он не из objc2-app-kit, а из базового objc2, доступен всегда),
# поэтому включаем в импорт всю цепочку, кроме NSObject
objc2-app-kit = { version = "0.3", features = ["NSWindow", "NSPanel", "NSResponder"] }
